#include "..\Example\Functions.hpp"
#include "..\Fishing\Functions.hpp"
#include "..\Farming\Functions.hpp"
#include "..\ShopSystem\Functions.hpp"
#include "..\ATM\Functions.hpp"
#include "..\methLab\Functions.hpp"