#include "..\Taser\RemoteFunctions.hpp"
#include "..\Example\RemoteFunctions.hpp"
#include "..\Ticketing\RemoteFunctions.hpp"
#include "..\Fishing\RemoteFunctions.hpp"
#include "..\Farming\RemoteFunctions.hpp"
#include "..\ShopSystem\RemoteFunctions.hpp"
#include "..\BasicMedical\RemoteFunctions.hpp"